const articleTypes = {
	SELECT_SINGLE_ARTICLE: 'SELECT_SINGLE_ARTICLE',
	SUCCESS_SELECT_SINGLE_ARTICLE: 'SUCCESS_SELECT_SINGLE_ARTICLE',
	FAIL_SELECT_SINGLE_ARTICLE: 'FAIL_SELECT_SINGLE_ARTICLE',

}

export default articleTypes