const contactTypes = {
	START_POST_CONTACT_MESSAGE: 'START_POST_CONTACT_MESSAGE',
	SUCCESS_POST_CONTACT_MESSAGE: 'SUCCESS_POST_CONTACT_MESSAGE',
	FAIL_POST_CONTACT_MESSAGE: 'FAIL_POST_CONTACT_MESSAGE',

}

export default contactTypes