const investmentEquityTypes = {
	SELECT_EQUITY_DATA: 'SELECT_EQUITY_DATA',
	SUCCESS_SELECT_EQUITY_DATA: 'SUCCESS_SELECT_EQUITY_DATA',
	FAIL_SELECT_EQUITY_DATA: 'FAIL_SELECT_EQUITY_DATA',

}

export default investmentEquityTypes